# Generated by Django 5.2.6 on 2025-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile/no-profile.png', null=True, upload_to='profile/'),
        ),
    ]
